### ISSUE TITLE
Incompatibility with setuptools version 18.6

### ISSUE THREAD

**Issue by siebenkopf** [bioidiap/bob.buildout#10]
Since version 18.6 of ``setuptools``, ``bob.buildout`` won't work any more (at least not for python 2). When running ``./bin/buildout``, error messages appear, such as:
```
...
File "build/bdist.linux-x86_64/egg/setuptools/command/develop.py", line 173, in install_wrapper_scripts
TypeError: super() argument 1 must be type, not classobj
```

(see: https://travis-ci.org/bioidiap/bob.core/jobs/93026198)

When using an older version of ``setuptools``:
```
$ python bootstrap-buildout.py  --setuptools-version 18.5
```
the compilation works as expected.

**Comment by anjos** [comment]
Will have a look. Thanks for the report!

**Comment by anjos** [comment]
The same command as above works flawlessly on my OS X machine, from a fresh bob.core install.

The problem shown up at the logs you pointed out are not related to `bob.buildout`. It seems related to a missing `class XYZ(object)` declaration inside setuptools/buildout itself from the error message, as `super()` can only be called on instances whose class derive from `object`.

IMO, this is temporary incompatibility between those tools. Re-running the build made it work OK on Travis as well.

**Comment by siebenkopf** [comment]
Yep, seems to have been an issue of setuptools version 18.6. With the new version 18.6.1 it seems to work again.
Sorry to have made you work on that, but I suspected that it is a permanent modification of setuptools that would require an update of bob.buildout.

Cheers
Manuel
