### ISSUE TITLE
Requirement parsing seems not to respect the environment with which the package is bootstrapped

### ISSUE THREAD

**Issue by siebenkopf** [bioidiap/bob.buildout#11]
I have an issue with versions of the same package (in this case, ``matplotlib``). I have system installation of ``matplotlib`` in version 1.3.1, which is found in ``/usr/lib/pymodules/python2.7``. I also have a ``virtualenv``, say in directory ``/virtual`` where I have installed some bob packages, which has ``matplotlib`` installed in version ``1.5.1``.

I have created a package, where I require ``matplotlib`` in version ``>=1.4``. The buildout.cfg looks like:
```
[buildout]
parts = scripts
eggs = matplotlib>=1.4

extensions = bob.buildout

[scripts]
recipe = bob.buildout:scripts
```
I have bootstrapped my package with ``/virtual/bin/python bootstrap-buildout.py``. Now, when I try to run ``./bin/buildout``, I get an exception:
```
  ...
  File "/virtual/local/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/virtual/local/lib/python2.7/site-packages/zc/buildout/buildout.py", line 666, in install
    installed_files = self[part]._call(recipe.install)
  File "/virtual/local/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1407, in _call
    return f()
  File "eggs/bob.buildout-2.0.9-py2.7.egg/bob/buildout/scripts.py", line 244, in install
    self.coverage.install_on_wrapped_env() + \
  File "eggs/bob.buildout-2.0.9-py2.7.egg/bob/buildout/python.py", line 78, in install_on_wrapped_env
    eggs, ws = self.working_set()
  File "eggs/bob.buildout-2.0.9-py2.7.egg/bob/buildout/script.py", line 138, in working_set
    ws = tools.filter_working_set_hard(ws, distributions)
  File "eggs/bob.buildout-2.0.9-py2.7.egg/bob/buildout/tools.py", line 342, in filter_working_set_hard
    dists = working_set.require(req)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 941, in require
    needed = self.resolve(parse_requirements(requirements))
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 833, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (matplotlib 1.3.1 (/usr/lib/pymodules/python2.7), Requirement.parse('matplotlib>=1.4'))
```

I have tried to replicate the issue, by:

```
$ /virtual/bin/python
>>> import pkg_resources
>>> ws = pkg_resources.WorkingSet()
>>> req = pkg_resources.Requirement.parse('matplotlib>=1.4')
>>> ws.resolve([req])
[matplotlib 1.5.1 (/virtual/lib/python2.7/site-packages),...]
```
So, when we are in the correct environment, it seems that the ``matplotlib`` can be resolved. When I do the same with system python, I get an error message comparable to the one above:

```
$ python
>>> import pkg_resources
>>> ws = pkg_resources.WorkingSet()
>>> req = pkg_resources.Requirement.parse('matplotlib>=1.4')
>>> ws.resolve([req])
...
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (matplotlib 1.3.1 (/usr/lib/pymodules/python2.7), Requirement.parse('matplotlib>=1.4'))
```

Hence, I assume that we are not in the correct environment when we call ``filter_working_set_hard``, or at least it does not respect the packages installed in ``/virtual``:
https://github.com/bioidiap/bob.buildout/blob/master/bob/buildout/tools.py#L335

**Comment by anjos** [comment]
I think this is why zc.buildout v2 does not anymore claim it can construct "isolated" environments (w.r.t. the bootstrapping python). Normally, at Idiap, we boot our virtualenvs without passing "--system-site-packages". Are you doing that? If so, I'd advise not to and install all required packages from scratch on your virtualenv.

**Comment by siebenkopf** [comment]
I am relying on the ``virtual-build.sh`` script from ``bob.nightlies``, which apparently includes the ``--system-site-packages`` flag:
https://gitlab.idiap.ch/biometric/bob.nightlies/blob/master/tools/virtual-build.sh#L98
although I didn't know that detail before. When you say you don't use this flag any more, I guess that you do not use the ``virtual-build.sh``? Shall we remove the flag inside there?

**Comment by anjos** [comment]
We should... It is a dangerous flag!

**Comment by siebenkopf** [comment]
Done. I will try out the new virtual-build.sh and see if it has solved this issue. But before I will push new versions of some of the packages.

**Comment by siebenkopf** [comment]
Unfortunately, with the new ``virtual_build.sh`` I cannot verify that this issue is actually solved -- as I do not have different versions of the same (external) packages installed any more. At least my issue is solved by not using that ``--system-site-packages`` flag, so I close this issue.
