### ISSUE TITLE
Not getting C++dependencies of python dependencies in the correct folder

### ISSUE THREAD

**Issue by siebenkopf** [bioidiap/bob.buildout#6]
Dear André,

it seems that your latest modifications did a bad job. With bob.buildout 2.0.3, there are again some issues with packages that I develop locally. Now, only dependencies of dependencies are not loaded correctly (I get the package from the global installation, not my locally developed package).
I have tried everything, like put the package in the eggs, in the setup.py, change the order of the packages, but nothing of that helped.

However, it seems to work well with bob.buildout 2.0.2. Maybe we should delete the latest version, or re-upload 2.0.2 as 2.0.4?

**Comment by anjos** [comment]
We must understand why that is. bob.buildout 2.0.2 will not work on other setups.

**Comment by siebenkopf** [comment]
The solution in version 2.0.4 seems to work properly.
