### ISSUE TITLE
'./bin/python script.py' will have wrong paths

### ISSUE THREAD

**Issue by siebenkopf** [bioidiap/bob.buildout#7]
The ``'PYTHONSTARTUP'`` hook:
https://github.com/bioidiap/bob.buildout/blob/master/bob/buildout/python.py#L66
to get the paths right that we have established in the ``./bin/python`` script only works for interactive shells:
https://docs.python.org/2/tutorial/interactive.html?highlight=pythonstartup#id1

Hence, it has no effect, when you run a ``script.py`` in the current directory, which requires the setup of the system:
```sh
$ ./bin/python script.py
```

However, you can get things right, when you
```python
import pkg_resources
```
as the first line in ``script.py``.

I am not sure if we need to take any action for this. I opened this bug mainly to keep track of this issue.

**Comment by tiagofrepereira2012** [comment]
I don't know if I understood correctly this issue, but I use to do this '``./bin/python script.py``'  all the time and works perfectly.

I will close this one, but if I understood it wrong, you can open it again.

**Comment by siebenkopf** [comment]
The problem seems to be, when you want to import from a mixed local / global installation, i.e., when you develop some packages and take the rest from ``bob-stable``. 
In this case, the local packages are ignored, unless you ``import pkg_resources`` before you load any ``bob`` package.

The ``'PYTHONSTARTUP'`` hook fixes that by adding a particular ``PYTHONSTARTUP`` file, which is executed before the python shell is opened, and which basically imports pkg_resources. 
Unfortunately, the ``PYTHONSTARTUP`` file is only valid for interactive shells, i.e., when you get a python prompt: ``./bin/python``. For the non-interactive shell (i.e., when you run a script using ``./bin/python script.py``, or inline ``./bin/python -c "import bob..."``), the ``'PYTHONSTARTUP'`` file is not read at all and, hence, the hook fails.

We have such a mixed environment on Travis, i.e., when we use some bob packages with wheels, which are installed globally. Hence, in the ``.travis.yml`` of any bob package, when running the ``./bin/python`` script inline, such as in: https://github.com/bioidiap/bob.ip.base/blob/master/.travis.yml#L25
I had to manually add the ``import pkg_resources``, otherwise the currently developed package would not have been found.

Since this issue has not been solved, I just re-open it. Anyways, we can also mark it as won't-fix since I don't see any solution to that, other than importing ``pkg_resources`` by hand.

**Comment by siebenkopf** [comment]
So, to reproduce the problem, please try (in the Idiap environment):

```
$ git clone https://github.com/bioidiap/bob.io.base.git
$ cd bob.bio.base
```
Compile using global installation of bob, and develop only bob.io.base:
```
$ /idiap/group/torch5spro/releases/bob-stable/py27/bin/python bootstrap-buildout.py
$ ./bin/buildout buildout:debug=false buildout:develop=. buildout:extensions=bob.buildout buildout:auto-checkout=
```

Check version of bob.io.base
```
$ ./bin/python -c "import bob.io.base; print(bob.io.base.__file__)"
$ ./bin/python -c "import pkg_resources; import bob.io.base; print(bob.io.base.__file__)"
$ ./bin/python
>>> import bob.io.base
>>> print(bob.io.base.__file__)
```
Although all three commands should return the same file, but the first one does not.

BTW: Apologies if the commands don't work exactly like that, but I couldn't ssh idiap any more to verify the command lines.

I hope, this makes the issue a bit more clear.

**Comment by siebenkopf** [comment]
This has been fixed by now (I don't remember, which was the commit that fixed it).
